# Site settings
title: Résidence Ella
description: "Résidence hôtelière de standing à Paris 15. Appartements du studio au F3, services hôteliers, spa, salle de sport et espace CoMeeting pour vos réunions."
url: "https://residence-ella.com" # URL de base du site
image: "/img/landing/header.jpg" # Image par défaut pour le partage RS

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-sitemap